### ISSUE TITLE
Question regarding pseudo mask generation

### ISSUE THREAD

**Issue by monjurulkarim** [ElementAI/wise_ils#6]
Hi, In the code where I can find the pseudo mask generation process? I want to save the pseudo masks. How can I do this?

**Comment by IssamLaradji** [comment]
You can obtain them from here:

https://github.com/facebookresearch/deepmask

**Comment by monjurulkarim** [comment]
@IssamLaradji  thanks for your quick response. Then how the PRM is helping in generating a pseudo mask? It would be very helpful for me if you could clarify this to me.

**Comment by IssamLaradji** [comment]
PRM is there to choose between the proposals.

**Comment by monjurulkarim** [comment]
@IssamLaradji  Thanks for the clarification.

**Comment by monjurulkarim** [comment]
@IssamLaradji One more question, are you saving the output from the PRM somewhere?
